### ISSUE TITLE
怎么构建呀？

### ISSUE THREAD

**Issue by jpgkudo** [querycap/harbor#189]
请教，怎么构建 arm64 离线包？

**Comment by morlay** [comment]
Docker/Containerd 本身支持离线导出导入
非容器化部署 的不清楚

**Comment by jpgkudo** [comment]
额，你这边不是构建了吗？

我明白容器和镜像可以导入导出，我的意思是该如何从 harbor 源码构建镜像，是这个意思呢。

**Comment by jpgkudo** [comment]
@morlay 
另外，想咨询下，这个 deploy 是什么意思？容器部署不是用 docker-compose 编排么？
![image](https://user-images.githubusercontent.com/51149477/141041669-dc752050-9f71-4b4b-8d31-4986f394ff60.png)

**Comment by morlay** [comment]
用我的分支 打 patch

https://github.com/querycap/harbor/blob/main/.github/workflows/docker-publish-images.yml#L117

按需构建

https://github.com/querycap/harbor/blob/main/.github/workflows/docker-publish-images.yml#L138

**Comment by morlay** [comment]
> @morlay 另外，想咨询下，这个 deploy 是什么意思？容器部署不是用 docker-compose 编排么？ ![image](https://user-images.githubusercontent.com/51149477/141041669-dc752050-9f71-4b4b-8d31-4986f394ff60.png)

k8s/k3s 
线上环境几乎不跑 docker 了

docker-compose 和官方的没区别，只需要改镜像 hub

**Comment by jpgkudo** [comment]
😂没了解太多，目前还在用 docker 跑。

“docker-compose 和官方的没区别” 这个官方是哪个官方？

**Comment by morlay** [comment]
goharbor

**Comment by jpgkudo** [comment]
好的  非常感谢！！
