### ISSUE TITLE
harbor-exporter 这个包没有？

### ISSUE THREAD

**Issue by mingtdlb** [querycap/harbor#191]
只有 harbor-exporter-base，x86 是这个 harbor-exporter。

docker-compose.yml 有么？

**Comment by morlay** [comment]
https://github.com/querycap/harbor/pkgs/container/harbor%2Fharbor-exporter

之前的 patch 有问题，exporter 忘记 push 了 
https://github.com/goharbor/harbor/compare/release-2.4.0...morlay:release-2.4.0

docker-compose 没区别，改镜像地址就好

**Comment by mingtdlb** [comment]
刚试了下，起不来，报错了。
![图片](https://user-images.githubusercontent.com/84701966/141262017-eabc2463-5615-4d59-9c0f-9271e7e184e0.png)

版本：v2.4.0

**Comment by 631068264** [comment]
@ghost 之后怎样解决。。。这东西根本没法用，有其他方法安装arm版本吗
